# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
# test
local.Url=jdbc:postgresql://localhost:5432/farmacybot
local.user=farmacybot
local.password=farmacybot

local.DriverClassName=org.postgresql.Driver
#local.JmxEnabled=true
local.LogAbandoned=true
local.MaxActive=10
local.MaxWait=30000
local.MaxIdle=3
local.MinIdle=1
local.InitialSize=10
#local.MinEvictableIdleTimeMillis=60000
local.RemoveAbandoned=false
local.RemoveAbandonedTimeout=600
local.TestOnBorrow=true
local.TestOnReturn=false
local.TestWhileIdle=false
local.TimeBetweenEvictionRunsMillis=30000
local.ValidationInterval=30000
local.ValidationQuery=SELECT 1
local.JdbcInterceptors=org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer
