# Configuraci\u00f3n b\u00e1sica de Log4j2
name=PropertiesConfig
status = error
#property.pathBase = ${sys:weblogic.domain.home}\servers\${sys:weblogic.Name}
property.pathBase = ${sys:jboss.server.log.dir}

#appenders = console, user, system
appenders=console, rolling
#appenders=rolling

# Configuraci\u00f3n del root logger que utiliza ambos appenders
rootLogger.level= debug
rootLogger.appenderRefs=ar_console,ar_rolling
rootLogger.appenderRef.ar_console.ref=STDOUT
rootLogger.appenderRef.ar_rolling.ref=userLog

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%c:%L] %m%n

appender.rolling.type = RollingFile
appender.rolling.name = userLog
appender.rolling.fileName = ${pathBase}/modbase.log
appender.rolling.filePattern = ${pathBase}/modbase-%d{yyyy-MM-dd}-%i.log
appender.rolling.layout.type=PatternLayout
#appender.rolling.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c:%L] %m%n
appender.rolling.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %m%n  
appender.rolling.policies.type=Policies
#appender.rolling.policies.startup.type = OnStartupTriggeringPolicy
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1
appender.rolling.policies.time.modulate = true
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 200MB
